### ISSUE TITLE
Get this to work with google-chrome?

### ISSUE THREAD

**Issue by Strykar** [xtknight/vdpau-va-driver-vp9#11]
@xtknight  Any chance this might work with google-chrome?

**Comment by C-512L** [comment]
> @xtknight Any chance this might work with google-chrome?

video decoding in google chrome is disabled at build time, unless chromium devs enable VA-API it its unlikely to happen
See: https://chromium-review.googlesource.com/c/chromium/src/+/2062356

**Comment by Strykar** [comment]
Ok, I was wondering since this, while not Google Chrome, patches for it - https://aur.archlinux.org/packages/chromium-vaapi/

**Comment by C-512L** [comment]
there are two main patchsets for vaapi as far as i know, the main difference is that one works with vdpau-va-driver.
Chromium's in-progress patch doesnt work with va-api.
Also, there are quite some chromium builds with va-api enabled in some linux distros:(this list is made by myself and based on what i can remember).
- (Snap)Ubuntu had a va-api branch but its actually disabled (maybe in future gets re-enabled) but i couldn test it.
- (AUR)Arch/Manjaro have chromium-vaapi package (i never used arch so idk if works with nvidia but i think it works).
- (Deb) OpenSUSE and Saikrishna Arcot chromium builds and opensuse ungoogled-chromium builds have the va-api patches and as i tried vdpau works via vdpau-va-driver-vp9 (https://linuxmint-user-guide.readthedocs.io/en/latest/chromium.html).
- NixOS as far i know has va-api patches too but idk if works with nvidia.
- Brave Browser OFFICIALLY supports va-api patches (but dont works with vdpau, maybe in future when vaapi patches are applied to official chromium, they would be a request to patch it to support vdpau too)
- Firefox supports va-api in wayland (v79) and Xorg (v80 nightly) but neither of them works with nvidia. I read that in firefox bugzilla this is vdpau-va-driver issue because which doesn't implement this function: vaExportSurfaceHandle

It could be interesting to get firefox to work with it with this fork

**Comment by Strykar** [comment]
Thanks for clearing that up, closing.
